# Site settings
title: My Territory
description: "Online Territory of Shikher Verma"  # used in site head

# register on google analytics and replace this token
google_analytics: UA-75681059-1
# disque comments are broken if you send http:// along with url, this url is same as the one given on disqus
disqus_url: shikherverma.com
disqus_id: shikherverma
# register on feedburner and replace this url
feedburner_url: https://feedburner.google.com/fb/a/mailverify?uri=programmer-wannabe&amp;loc=en_US

# footer details
github_username:  shikherverma
facebook_username:  shikherverma42
email: root@shikherverma.com
stackoverflow_username: 6764571/shikher-verma
twitter_username : shikherverma42
copyright_name: Shikher Verma

# used for portfolio on home page
collections:
  - portfolio

# used to estimate reading time
wpm: 150

# Build settings
markdown: kramdown
highlighter: rouge
exclude: ["less","node_modules","Gruntfile.js","package.json","README.md"]
port: 8888
permalink: /blog/:title

# jekyll-paginate. for paginating blog posts.
paginate: 5
paginate_path: blog/page:num

# gem dependencies
gems: [jekyll-paginate, jekyll-feed, jekyll-gist]
